{
	"version": 1534055007,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/winter_dummy-sheet0.png",
		"images/winter_background-sheet0.png",
		"images/bird-sheet0.png",
		"images/bird-sheet1.png",
		"images/ground_rock-sheet0.png",
		"images/bottomice-sheet0.png",
		"images/upice-sheet0.png",
		"images/wfood1-sheet0.png",
		"images/wfood1-sheet1.png",
		"images/wfood1-sheet2.png",
		"images/food2-sheet0.png",
		"images/summerdummy-sheet0.png",
		"images/summerbackground-sheet0.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/toppipe-sheet0.png",
		"images/bottompipe-sheet0.png",
		"images/bird2-sheet0.png",
		"images/bird2-sheet1.png",
		"images/rainybackground-sheet0.png",
		"images/particles.png",
		"images/splash.png",
		"images/raindrop-sheet0.png",
		"images/sfood3-sheet0.png",
		"images/rfood5-sheet0.png",
		"images/rfood5-sheet1.png",
		"images/rfood5-sheet2.png",
		"images/bird3-sheet0.png",
		"images/button_quit-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/button_forward_logo-sheet0.png",
		"images/dummy_reference-sheet0.png",
		"images/title_screen_background-sheet0.png",
		"images/button_home-sheet0.png",
		"images/button_back-sheet0.png",
		"images/objectives_screen_background-sheet0.png",
		"images/sprite-sheet0.png",
		"images/benefits_screen_background-sheet0.png",
		"images/menu_screen_background-sheet0.png",
		"images/button_play-sheet0.png",
		"images/button_benefits-sheet0.png",
		"images/button_objectives-sheet0.png",
		"images/button_credits-sheet0.png",
		"images/dragtocontrolscrolling-sheet0.png",
		"images/credits_screen_background-sheet0.png",
		"images/dragtocontrolscrolling2-sheet0.png",
		"images/credits_list-sheet0.png",
		"media/dark_rainy_night(ambience).ogg",
		"media/summer sunday.m4a",
		"media/summer sunday.ogg",
		"media/christmas synths.ogg",
		"media/carnivalrides.ogg",
		"media/wscream_2 (1).m4a",
		"media/wscream_2 (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}